name: NodeJS with Grunt

on:
  workflow_dispatch:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
            
    - name: Build
      run: |
        pnpm install
        pnpm dev
        
